# Generated by Django 3.1.6 on 2021-03-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('pikabu_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Post URL', verbose_name='URL')),
                ('created_at', models.DateTimeField(help_text='Date and time when the task was created', verbose_name='Created at')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='Date and time when the post page was fetched', null=True, verbose_name='Fetched at')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Date and time when the task was finished', null=True, verbose_name='Finished at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], help_text='Current status', max_length=100, verbose_name='Status')),
                ('status_message', models.TextField(help_text='Status message such as error description', verbose_name='Status message')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pikabu_id', models.IntegerField(help_text='The ID of the comment on pikabu.ru.', verbose_name='Pikabu ID')),
                ('pikabu_parent_id', models.IntegerField(blank=True, help_text='The ID of the parent comment on pikabu.ru.', null=True, verbose_name='Pikabu Parent ID')),
                ('text', models.TextField(help_text='The text of the comment.', verbose_name='Text')),
                ('date', models.DateTimeField(help_text='The date of the comment.', verbose_name='Date')),
                ('rating', models.IntegerField(help_text='The rating of the comment.', verbose_name='Rating')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='The parent comment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='comments.comment', verbose_name='Parent comment')),
                ('post', models.ForeignKey(help_text='The post', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post')),
                ('user', models.ForeignKey(help_text='The creator of the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pikabu_users.pikabuuser', verbose_name='User')),
            ],
        ),
    ]
