# Generated by Django 3.1.6 on 2021-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Post URL', verbose_name='URL')),
                ('created_at', models.DateTimeField(help_text='Date and time when the task was created', verbose_name='Created at')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='Date and time when the post page was fetched', null=True, verbose_name='Fetched at')),
                ('finished_at', models.DateTimeField(blank=True, help_text='Date and time when the task was finished', null=True, verbose_name='Finished at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], help_text='Current status', max_length=100, verbose_name='Status')),
            ],
        ),
    ]
