# Generated by Django 3.1.6 on 2021-03-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pikabu_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The url of the post on pikabu.ru.', verbose_name='URL')),
                ('is_processed', models.BooleanField(default=False, help_text='Does the post contain processed values or url only?', verbose_name='Is processed?')),
                ('user', models.ForeignKey(blank=True, help_text='The creator of the post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pikabu_users.pikabuuser', verbose_name='User')),
            ],
        ),
    ]
